alias b='bundle'
alias d='docker'
alias dc='docker-compose'
alias g='git'
alias hq='ghq get --look (ghq list | fzf)'
alias k='kubectl'
alias ll='ls -al'
alias ln='ln -v'
alias runghc='stack runghc --'
alias s='skaffold'
alias t='tig'
alias y='yarn'

# Linux
alias open='xdg-open'
alias pbcopy='xclip -selection clipboard'
