#!/bin/sh

touch "$HOME"/.psqlrc.local

if [ -e "$HOME"/.vim/autoload/plug.vim ]; then
  vim -E -s +PlugUpgrade +qa
else
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim -u "$HOME"/.vimrc.bundles +PlugUpdate +PlugClean! +qa

systemctl --user enable imwheel
systemctl --user restart imwheel

fish -c '
if not functions -q fisher
  curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
end
'

fish -c "
fisher install 0rax/fish-bd jethrokuan/fzf jethrokuan/z laughedelic/pisces oh-my-fish/plugin-foreign-env oh-my-fish/plugin-sudope rafaelrinaldi/pure daenney/rbenv evanlucas/fish-kubectl-completions
"

go get -u github.com/motemen/ghq
env CGO_ENABLED=0 GO111MODULE=on go get -u -ldflags="-s -w" github.com/gokcehan/lf

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
~/.tmux/plugins/tpm/bindings/install_plugins

curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash

curl https://get.volta.sh | bash
volta install node

curl https://nixos.org/nix/install | sh

# Interactive
cat <<TEXT
set -Ux fish_user_paths $HOME/go/bin $HOME/.cargo/bin $HOME/.rbenv/bin/ $fish_user_paths
Setup:
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
TEXT

echo 'set -g fish_user_paths path/to/bin $fish_user_paths'

reset -Q
